# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: STPDF-docs
description: >- # this means to ignore newlines until "baseurl:"
  STPDF allows you to easily create PDFs from scanned images, 
  it can also deskew images (removes image rotation), It is free and open-source.
baseurl: "/STPDF-docs" # the subpath of your site, e.g. /blog
url: "https://hallowf.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  hallowf

# Build settings
remote_theme: pmarsceill/just-the-docs
# encoding
encofing: utf-8


# Theme settings
search_enabled: false
aux_links:
    "STPDF on GitHub":
      - "//github.com/hallowf/STPDF"

ga_tracking: UA-100382035-6

# Jekyll-multiple-languages plugin settings
languages: ["en", "pt"]
exclude_from_localizations: ["assets", "js", "imgs", "README.md"]
# fix for missing languages on main build
langs: ["en","pt"]


# SEO tag stuff
social:
  name: hallowf
  links:
    - https://www.facebook.com/Hallows.Tech.Lab/
    - https://www.instagram.com/hallowstechlab/

plugins:
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
